---
title: "IPD_MICE"
output: pdf_document
---

```{r, message = FALSE, warning = FALSE}
library(mice)
library(VIM)
library(optmatch)
library(survival)
library(rbounds) # Matching package is automatically loaded with rbounds
```

```{r}
ipd <- read.csv("IPD.csv")
v.list <- c("PID","Study","Site","Group",
            "Age","Gender",
            "modmotscpre","modmotscpost",
            "EQ5Dpre",
            "TFC",
            "UHDRStV1",
            "SDMTpre")
df <- ipd[,v.list]
```

# use mice for looking at missing data pattern
```{r}
df_mice <- df[,-c(1:6)]
md.pattern(df_mice)
aggr_plot <- aggr(df_mice, col=c('navyblue','red'), 
                  numbers=TRUE, sortVars=TRUE, 
                  labels=names(df_mice), cex.axis=0.7, cex.numbers=0.7, 
                  gap=3, 
                  ylab=c("Histogram of missing data","Pattern"))

# exclude participants with missing outcome data
df2 <- df[!is.na(df$modmotscpost),]
df_mice2 <- df2[,-c(1:6)]
md.pattern(df_mice2)
aggr_plot2 <- aggr(df_mice2, col=c('navyblue','red'),
                   numbers=TRUE, sortVars=TRUE, 
                   ylabs=c("Histogram of missing data","Pattern"),
                   labels=names(df_mice),
                   cex.axis=0.7, cex.numbers=0.7, gap=3)
```

# impute the missing data
```{r}
load("imp30.Rdata")
# imp30 <- mice(df2,
#               method='pmm',
#               m=30, 
#               maxit=10, 
#               seed=2019) 
# summary(imp30)
```

# propensity score
## functions
```{r}
# This function displays an overlap histogram for "lps" across "trt" groups
ovlp <- function(trt, lps)
{
  # statistical test of difference in mean
  tt <- t.test(x = lps[trt==1], y = lps[trt==0], alternative = "two.sided",
               var.equal = FALSE)$p.value
  # statistical test of difference in distribution
  ks <- ks.test(x = lps[trt==1], y = lps[trt==0], alternative = "two.sided")$p.value
  
  par(mfrow = c(2,1))
  rc <- range(lps)
  brks <- seq(from = rc[1] - diff(rc)/20, to = rc[2] + diff(rc)/20, by = diff(rc)/20)
  hist(lps[trt==1], breaks = brks, xlab = "", main = "Treated Cases",
       freq = FALSE)
  d1 <- density(lps[trt==1])
  lines(d1, col = 2, lwd = 1, lty = 1)
  abline(v = c(range(lps[trt==1])), col = 3, lty = 2)
  hist(lps[trt==0], breaks = brks, xlab = "", main = "Control Cases",
       freq = FALSE)
  d2 <- density(lps[trt==0])
  lines(d2, col = 2, lwd = 1, lty = 1)
  abline(v = c(range(lps[trt==0])), col = 3, lty = 2)
  par(mfrow = c(1,1))
}

# Note that ovlp_ind requires that package optmatch be loaded
ovlp_ind <- function(trt, lps, caliper = 0.1)
{
  nt <- sum(trt == 1); nc <- sum(trt == 0)
  SDpool <- sqrt( ( (nt - 1)*var(lps[trt == 1]) + (nc - 1)*var(lps[trt == 0]) ) / 
                    (nt + nc - 2) )
  # get abs(distance) for each treat/control pairing
  diffs <- match_on(trt ~ lps, method = "euclidean")
  smds <- diffs/SDpool # standardize differences by dividing by pooled SD
  fun <- function(vec) {min(vec) <= caliper}
  trtOvlp <- apply(smds, 1, fun)   ## TRUEs are overlapping
  ctrlOvlp <- apply(smds, 2, fun)  ## FALSEs are not
  drop1 <- which(trt==1)[!trtOvlp]
  drop0 <- which(trt==0)[!ctrlOvlp]
  ind <- !logical(length(lps))
  ind[c(drop1, drop0)] <- FALSE
  ind
}
```

## propensity score matching
```{r}
# create empty dataframe to store results of each imputed dataset
PID <- df2$PID
df_ps <- data.frame(PID)
df_logit_ps <- data.frame(PID)
df_Y1hats <- data.frame(PID)
df_Y0hats <- data.frame(PID)

PID <- df2[which(df2$Group == "intervention"),"PID"]
df_Y0hatsATT <- data.frame(PID)

# create empty list to store ATE/ATT of each imputed dataset
ATElist <- c()
ATTlist <- c()

for (i in 1:30){
  imp <- complete(imp30, i)
  glm <- glm(Group ~ Age + Gender + I(modmotscpre^2) + EQ5Dpre + I(TFC^2) + UHDRStV1 +SDMTpre,
             data = imp, family = "binomial")
  ps <- predict(glm, type = "response")
  logit_ps <- log(ps/(1 - ps))
  
  # assess overlap
  group <- ifelse(imp$Group == "control", 0, 1) 
  # ovlp(trt = group, lps = logit_ps)
  
  # examine overlap after eliminating non-overlapping cases
  ovlp_ind1 <- ovlp_ind(trt = group, lps = logit_ps, caliper = .2) ## create overlap indicator
  sum(ovlp_ind1)
  table(ovlp_ind1, group)
  # ovlp(trt = group[ovlp_ind1], lps = logit_ps[ovlp_ind1])
  
  # create a subset of only overlapping cases
  imp_ovlp <- imp[ovlp_ind1,]
  
  # re-estimate PS using overlapping data
  glm_ovlp <- glm(Group ~ Age + Gender + I(modmotscpre^2) + EQ5Dpre + I(TFC^2) + UHDRStV1 +SDMTpre,
                  data = imp_ovlp, family = "binomial")
  ps_ovlp <- predict(glm_ovlp, type = "response")
  logit_ps_ovlp <- log(ps_ovlp/(1 - ps_ovlp))
  
  ## store results
  temp_ps <- data.frame(imp_ovlp$PID, ps_ovlp); colnames(temp_ps) <- c("PID", i)
  df_ps <- merge(df_ps, temp_ps, all = T)
 
  temp_logit_ps <- data.frame(imp_ovlp$PID, logit_ps_ovlp); colnames(temp_logit_ps) <- c("PID", i)
  df_logit_ps <- merge(df_logit_ps, temp_logit_ps, all = T)
  
  # regression estimation
  ## create a data subset for group intervention
  dat1 <- subset(imp_ovlp, subset = Group == "intervention")
  ## create a data subset for group control
  dat0 <- subset(imp_ovlp, subset = Group == "control")
  ## regression model
  lmY1 <- lm(modmotscpost ~  Age + Gender + I(modmotscpre^2) + EQ5Dpre + I(TFC^2) + UHDRStV1 +SDMTpre, 
             data = dat1)
  lmY0 <- lm(modmotscpost ~  Age + Gender + I(modmotscpre^2) + EQ5Dpre + I(TFC^2) + UHDRStV1 +SDMTpre, 
             data = dat0)
  ## ATE
  Y1hats <- predict(lmY1, newdata = imp_ovlp)
  Y0hats <- predict(lmY0, newdata = imp_ovlp)
  ATE <- mean(Y1hats - Y0hats)
  ATElist <- c(ATElist, ATE)
  
  ## ATT
  Y0hatsATT <- predict(lmY0, newdata = dat1)
  ATT <- mean(dat1$modmotscpost - Y0hatsATT)
  ATTlist <- c(ATTlist, ATT)

  ## store results
  temp_Y1hats <- data.frame(imp_ovlp$PID, Y1hats); colnames(temp_Y1hats) <- c("PID", i)
  df_Y1hats <- merge(df_Y1hats, temp_Y1hats, all = T)
  
  temp_Y0hats <- data.frame(imp_ovlp$PID, Y0hats); colnames(temp_Y0hats) <- c("PID", i)
  df_Y0hats <- merge(df_Y0hats, temp_Y0hats, all = T)
  
  temp_Y0hatsATT <- data.frame(dat1$PID, Y0hatsATT); colnames(temp_Y0hatsATT) <- c("PID", i)
  df_Y0hatsATT <- merge(df_Y0hatsATT, temp_Y0hatsATT, all = T)
}
```

## pooled predictions of linear regression
```{r}
# ATE
## method 1 - average Y1hats/Y0hats of 30 imputed datasets and then calculate the ATE
Y1hats <- rowMeans(df_Y1hats[,-1])
Y0hats <- rowMeans(df_Y0hats[,-1])
(ATE1 <- mean(Y1hats - Y0hats, na.rm = T))

## method 2 - calculate the ATE of each imputed dataset in the previous loop
(ATE2 <- mean(ATElist))
t.test(ATElist, conf.level = 0.95)

## method 3 - create a loop to calculate the ATE of each imputed dataset based on the Y1hats/Y0hats dataframes
ATElist3 <- c()
for (i in c(1:30)){
  ATE <- mean(df_Y1hats[,i+1] - df_Y0hats[,i+1], na.rm = T)
  ATElist3 <- c(ATElist3, ATE)
}
(ATE3 <- mean(ATElist3))

# ATT
## method 1
df_Y0hatsATT$Y0hatsATT <- rowMeans(df_Y0hatsATT[,-1])
df_ATT <- merge(df2[which(df2$Group == "intervention"), c("PID","modmotscpost")], df_Y0hatsATT[,c(1,32)])
(ATT1 <- mean(df_ATT$modmotscpost - df_ATT$Y0hatsATT, na.rm = T))

## method 2
(ATT2 <- mean(ATTlist))
t.test(ATTlist, conf.level = 0.95)
```

# sensitivity analysis
```{r}
# use the 1st imputed dataset
imp1 <- complete(imp30, 1)

Y <- imp1$modmotscpost # the outcome of interest
Tr <- ifelse(imp1$Group == "control", 0, 1) # the treatment of interest
ps <- glm(Group ~ Age + Gender + I(modmotscpre^2) + EQ5Dpre + I(TFC^2) + UHDRStV1 +SDMTpre,
          data = imp1, family = "binomial")

# match without replacement
Match <- Match(Y = Y, Tr = Tr, X = ps$fitted, replace = FALSE)

# provide Rosenbaum’s bounds for the p-values from Wilcoxon’s signed rank test
psens(Match, Gamma = 2, GammaInc = 0.1)

# provides Rosenbaum’s bounds for the additive effect due to treatment
hlsens(Match, Gamma = 2, GammaInc = 0.1, 0.1)
```