---
title: "Motor Subscore vs Sitting Task"
subtitle: "Trunk and UE"
output: pdf_document
---

```{r}
library(ggplot2)
setwd("~/Desktop/NRL")

# iWear
iwear <- read.csv("iWear/iWear_complete_0625.csv")
df_subscore <- iwear[c("as_correct", "Balance_Subscore", "Chorea_Subscore_Trunk_UE")]

# APDM
apdm <- read.csv("APDM/Sitting Postural Sway.csv", stringsAsFactors=FALSE)
apdm$X[1:20] <- paste0("IW", substr(apdm$X[1:20],3,4), "GHI")
## Postural Sway - Acc - Jerk (m^2/s^5) / Postural Sway - Acc - Mean Velocity (m/s)
## Postural Sway - Acc - RMS Sway (m/s^2) / Postural Sway - Angles - Sway Area (degrees^2)
df_sway <- apdm[c(1,12,15,21,30)]
colnames(df_sway)[1] <- "as_correct"

# merge
df <- merge(df_subscore, df_sway, sort = F)
## remove control group
df <- na.omit(df)
```

# Balance
```{r}
ggplot(df) +
  geom_point(aes(x = Postural.Sway...Acc...Jerk..m.2.s.5., y = Balance_Subscore)) +
  labs(title = "Balance vs Jerk",
       subtitle = cor(df$Postural.Sway...Acc...Jerk..m.2.s.5., df$Balance_Subscore),
       x = "Jerk (m^2/s^5)", y = "Balance")
cor.test(df$Postural.Sway...Acc...Jerk..m.2.s.5., df$Balance_Subscore)

ggplot(df) +
  geom_point(aes(x = Postural.Sway...Acc...Mean.Velocity..m.s., y = Balance_Subscore)) +
  labs(title = "Balance vs Mean Velocity",
       subtitle = cor(df$Postural.Sway...Acc...Mean.Velocity..m.s., df$Balance_Subscore),
       x = "Mean Velocity (m/s)", y = "Balance")
cor.test(df$Postural.Sway...Acc...Mean.Velocity..m.s., df$Balance_Subscore)

ggplot(df) +
  geom_point(aes(Postural.Sway...Acc...RMS.Sway..m.s.2., y = Balance_Subscore)) +
  labs(title = "Balance vs RMS Sway",
       subtitle = cor(df$Postural.Sway...Acc...RMS.Sway..m.s.2., df$Balance_Subscore),
       x = "RMS Sway (m/s^2)", y = "Balance")
cor.test(df$Postural.Sway...Acc...RMS.Sway..m.s.2., df$Balance_Subscore)

ggplot(df) +
  geom_point(aes(Postural.Sway...Angles...Sway.Area..degrees.2., y = Balance_Subscore)) +
  labs(title = "Balance vs Sway Area",
       subtitle = cor(df$Postural.Sway...Angles...Sway.Area..degrees.2., df$Balance_Subscore),
       x = "Sway Area (degrees^2)", y = "Balance")
cor.test(df$Postural.Sway...Angles...Sway.Area..degrees.2., df$Balance_Subscore)
```

# Chorea
```{r}
ggplot(df) +
  geom_point(aes(x = Postural.Sway...Acc...Jerk..m.2.s.5., y = Chorea_Subscore_Trunk_UE)) +
  labs(title = "Chore vs Jerk",
       subtitle = cor(df$Postural.Sway...Acc...Jerk..m.2.s.5., df$Chorea_Subscore_Trunk_UE),
       x = "Jerk (m^2/s^5)", y = "Chorea")
cor.test(df$Postural.Sway...Acc...Jerk..m.2.s.5., df$Chorea_Subscore_Trunk_UE)

ggplot(df) +
  geom_point(aes(x = Postural.Sway...Acc...Mean.Velocity..m.s., y = Chorea_Subscore_Trunk_UE)) +
  labs(title = "Chore vs Mean Velocity",
       subtitle = cor(df$Postural.Sway...Acc...Mean.Velocity..m.s., df$Chorea_Subscore_Trunk_UE),
       x = "Mean Velocity (m/s)", y = "Chorea")
cor.test(df$Postural.Sway...Acc...Mean.Velocity..m.s., df$Chorea_Subscore_Trunk_UE)

ggplot(df) +
  geom_point(aes(Postural.Sway...Acc...RMS.Sway..m.s.2., y = Chorea_Subscore_Trunk_UE)) +
  labs(title = "Chore vs RMS Sway",
       subtitle = cor(df$Postural.Sway...Acc...RMS.Sway..m.s.2., df$Chorea_Subscore_Trunk_UE),
       x = "RMS Sway (m/s^2)", y = "Chorea")
cor.test(df$Postural.Sway...Acc...RMS.Sway..m.s.2., df$Chorea_Subscore_Trunk_UE)

ggplot(df) +
  geom_point(aes(Postural.Sway...Angles...Sway.Area..degrees.2., y = Chorea_Subscore_Trunk_UE)) +
  labs(title = "Chore vs Sway Area",
       subtitle = cor(df$Postural.Sway...Angles...Sway.Area..degrees.2., df$Chorea_Subscore_Trunk_UE),
       x = "Sway Area (degrees^2)", y = "Chorea")
cor.test(df$Postural.Sway...Angles...Sway.Area..degrees.2., df$Chorea_Subscore_Trunk_UE)
```